name: Build and deploy
on:
  push:
    branches: [main]
  workflow_dispatch:
  
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@latest
      - name: Upload artifact
        uses: actions/upload-artifact@latest
        with:
          path: /
        
  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@latest
      - name: Download artifact
        uses: actions/download-artifact@latest
      - name: Sync files to hosting
        uses: SamKirkland/FTP-Deploy-Action@4.0.0
        with:
          server: ftp.92.63.169.233
          username: github@92.63.169.233
          password: ${{ secrets.ftp_password }}
